### ISSUE TITLE
Crashes on 1.16.1

### ISSUE THREAD

**Issue by calloatti** [MarioAndWeegee3/Fabric-Resource-Loader#1]
fabric-resource-loader-1.0.1.jar crashes on MC 1.16.1 could you please update it? Thank you!

https://paste.ee/p/jMe0k

**Comment by leo60228** [comment]
Looks like a fix was pushed to this repo a few hours ago. I've heard that Curse is taking a while to approve updates due to the pandemic.

**Comment by leo60228** [comment]
Well, I assumed the commit message was joking because of how small this mod is, but it does seem to actually be unfinished. There isn't much, I'm probably going to PR in about 20 minutes.

**Comment by MarioAndWeegee3** [comment]
Fixed in 1.1.0 (thanks leo60228)
